name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  deploy-github:
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub
        run: ./mvnw --batch-mode --settings settings.xml -Pgithub clean deploy

  deploy-sonatype:
    name: Sonatype
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG Keys
        run: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys ${{ secrets.GPG_PUBLIC_KEY }}
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --no-tty --batch --yes -
      - name: Deploy to Sonatype
        run: ./mvnw --batch-mode --settings settings.xml -Possrh,sign clean deploy
